namespace SharedUtils.Api.ResponseViewModels
{
    /// <summary>
    /// Response sent to client after Post Comment Request.
    /// </summary>
    public class ResponseAddCommentViewModel
    {
        public enum OperationResult
        {
            Invalid,
            AuthorizationFailed,
            CommentAdded,
            CommentEdited,
        }

        public ResponseAddCommentViewModel() { }
        public ResponseAddCommentViewModel(OperationResult retcode) { Retcode = retcode; }

        /// <summary>
        /// Operation Result
        /// </summary>
        public OperationResult Retcode { get; set; }
        /// <summary>
        /// Post Id generated by OpenPost System.
        /// </summary>
        public string CommentId { get; set; }
        /// <summary>
        /// Parent Post Id if post is child
        /// </summary>
        public string ParentCommentId { get; set; }
        /// <summary>
        /// Current Post depth (for tree)
        /// </summary>
        public int Depth { get; set; }
        /// <summary>
        /// Current Post Title
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// Current Post Content
        /// </summary>
        public string Content { get; set; }
        /// <summary>
        /// Author Name
        /// </summary>
        public string Author { get; set; }
        /// <summary>
        /// Author Avatar Url
        /// </summary>
        public string AvatarUrl { get; set; }
        /// <summary>
        /// Author url (profile)
        /// </summary>
        public string ProfileUrl { get; set; }
    }
}
